# TIL 1125

## 예외처리

### Error

- 하드웨어에서 발생

### exception

- 소프트웨어로 제어할 수 있는 error

#### Try ~ Catrch

```java
try {
    // try문: 예외발생 가능성이 있는 코드와
    // 가능성이 없는 코드를 기술
    // 중첩가능
    Scanner scan = new Scanner(System.in);
    System.out.print("정수입력=");
    int num = scan.nextInt();
    System.out.println("num="+num);
}catch(InputMismatchException ime) {// 예외발생시 실행되는 영역
	System.out.println("문자를 입력할 수 없습니다.");
}catch(exception e){
    // 앞서 정한 예외처리 이외의 모든 에러
    // 가장 아래에 작성
}finally{
    // 무조건 실행(예외가 발생하든 상관X)
    try {
		// 중첩가능
	}catch(Exception e) {}
}
System.out.println("The End");
```



#### 메서드 이용

- Throw 이용

```java
public class ExceptionTest3 {
	Scanner scan = new Scanner(System.in);
	public ExceptionTest3() {		
		// 2. 메서드 이용해서 예외처리
	}
	
	public void method1() throws ArrayIndexOutOfBoundsException {
		int num = scan.nextInt();
		int num2 = scan.nextInt();
		method2(num, num2);
	}
	public void method2(int num, int num2) throws ArrayIndexOutOfBoundsException {
		int result = num / num2;
		System.out.printf("%d / %d = %d", num, num2, result);
		method3(num);
	}
	public void method3(int num) throws ArrayIndexOutOfBoundsException {
		int arr[] = new int[num];
		arr[num] = 562;
	}
	
	public static void main(String[] args) throws ArrayIndexOutOfBoundsException {
		ExceptionTest3 t = new ExceptionTest3();
        // 시작점에서 Try문 적용
		try {
			t.method1();			
		}catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("배열idx 예외발생");
		}
	}
}
```



### 에외 발생시키기

#### 예외상속받기



## 컬렉션

### ValueObject

- 데이터를 



